const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')
const test = require('node:test')

const frontendRoot = path.resolve(__dirname, '../..')

test('Eagle AI branding is wired into the app shell and session loader', () => {
	const manifest = JSON.parse(fs.readFileSync(path.join(frontendRoot, 'manifest.json'), 'utf8'))
	const pages = JSON.parse(fs.readFileSync(path.join(frontendRoot, 'pages.json'), 'utf8'))
	const sessionGate = fs.readFileSync(path.join(__dirname, 'session-gate.vue'), 'utf8')
	const nativeSplashBridge = fs.readFileSync(
		path.join(frontendRoot, 'common', 'launch', 'eagle-native-splash.js'),
		'utf8'
	)
	const eagleMark = path.join(frontendRoot, 'static', 'branding', 'eagle-mark.png')
	const appIcon = path.join(frontendRoot, 'static', 'branding', 'app-icon.png')

	assert.equal(manifest.name, 'Eagle AI')
	assert.equal(manifest['app-plus'].splashscreen.waiting, false)
	assert.equal(manifest['app-plus'].splashscreen.autoclose, true)
	assert.equal(manifest['app-plus'].splashscreen.alwaysShowBeforeRender, false)
	assert.equal(pages.globalStyle.navigationBarTitleText, 'Eagle AI')
	const sessionGateRoute = pages.pages.find(item => item.path === 'pages/launch/session-gate')
	assert.equal(sessionGateRoute?.style?.navigationStyle, 'custom')
	assert.equal(sessionGateRoute?.style?.backgroundColor.toLowerCase(), '#0b0d0c')
	assert.equal(sessionGateRoute?.style?.navigationBarTitleText, undefined)
	assert.match(sessionGate, /eagle-mark\.png/)
	assert.match(sessionGate, /eagle-shimmer-sweep/)
	assert.match(sessionGate, /background:\s*#0[Bb]0[Dd]0[Cc]/)
	assert.match(sessionGate, /--eagle-shimmer-delay/)
	assert.match(sessionGate, /--eagle-shimmer-play-state/)
	assert.doesNotMatch(sessionGate, /radial-gradient\(circle at 78% 18%/)
	assert.match(sessionGate, /onReady\(\)\s*\{\s*this\.startFrontendShimmer\(\)/)
	assert.doesNotMatch(sessionGate, /onReady\(\)\s*\{[\s\S]{0,180}dismissNativeSplash/)
	assert.doesNotMatch(sessionGate, /go\(url\)\s*\{[\s\S]{0,320}dismissNativeSplash/)
	assert.match(sessionGate, /revealSessionGate\('session-error'\)/)
	assert.match(sessionGate, /revealSessionGate\('route-failed'\)/)
	assert.match(sessionGate, /revealSessionGate\(reason\)[\s\S]{0,420}dismissNativeSplashAfterPaint\(reason\)/)
	assert.match(nativeSplashBridge, /getCycleOffsetMillis/)
	assert.match(nativeSplashBridge, /SHIMMER_CYCLE_MILLIS\s*=\s*1900/)
	assert.match(nativeSplashBridge, /ALLOWED_DISMISS_REASONS/)
	assert.match(nativeSplashBridge, /controller\.dismiss\(reason\)/)
	assert.equal(fs.existsSync(eagleMark), true)
	assert.equal(fs.existsSync(appIcon), true)
})
