package com.example.temperate.service.registration.enums;

/**
 * 枚举注册流程向传输层暴露的稳定业务错误码。
 */
public enum RegistrationErrorCode {
    INVALID_INPUT,
    INVALID_PASSWORD,
    PASSWORD_STRENGTH_INSUFFICIENT,
    PASSWORD_MISMATCH,
    AUTH_REGISTER_UNAVAILABLE,
    REGISTRATION_FLOW_NOT_FOUND,
    REGISTRATION_FLOW_EXPIRED,
    REGISTRATION_FLOW_FORBIDDEN,
    HUMAN_VERIFICATION_REQUIRED,
    EMAIL_VERIFICATION_REQUIRED,
    PHONE_VERIFICATION_REQUIRED,
    VERIFICATION_COOLDOWN,
    VERIFICATION_SEND_LIMIT,
    VERIFICATION_CODE_INVALID,
    VERIFICATION_CODE_EXPIRED,
    VERIFICATION_CODE_ATTEMPTS_EXHAUSTED,
    VERIFICATION_CHANNEL_UNSUPPORTED,
    VERIFICATION_DELIVERY_FAILED,
    DELIVERY_UNAVAILABLE,
    TURNSTILE_REJECTED,
    REGISTRATION_ALREADY_COMPLETING,
    REGISTRATION_PERSISTENCE_FAILED
}
