package com.example.temperate.service.admin;

/**
 * 定义管理员初始化、登录、会话和外部人机验证向 Web 层暴露的稳定错误码。
 */
public enum AdminErrorCode {
    ADMIN_ALREADY_INITIALIZED,
    ADMIN_NOT_INITIALIZED,
    ADMIN_CONFIG_INVALID,
    ADMIN_CSRF_CONFIGURATION_INVALID,
    ADMIN_DISABLED,
    ADMIN_IDENTITY_INVALID,
    ADMIN_FLOW_INVALID,
    ADMIN_FLOW_EXPIRED,
    ADMIN_RATE_LIMITED,
    HCAPTCHA_REJECTED,
    HCAPTCHA_UNAVAILABLE,
    ADMIN_CREDENTIALS_INVALID,
    ADMIN_SESSION_INVALID,
    ADMIN_PREAUTH_REQUIRED,
    ADMIN_SESSION_LIMIT_REACHED,
    ADMIN_PHONE_CHANNEL_INVALID,
    ADMIN_VERIFICATION_INVALID,
    ADMIN_PASSWORD_INVALID,
    ADMIN_MAIL_INSPECTION_INVALID_REQUEST,
    ADMIN_MAIL_INSPECTION_IDEMPOTENCY_KEY_INVALID,
    ADMIN_MAIL_INSPECTION_IDEMPOTENCY_CONFLICT,
    ADMIN_MAIL_INSPECTION_SUBMISSION_INCOMPLETE,
    ADMIN_MAIL_INSPECTION_JOB_NOT_FOUND,
    ADMIN_MAIL_INSPECTION_JOB_CONFLICT,
    ADMIN_MAIL_INSPECTION_SSE_CONNECTION_LIMIT,
    ADMIN_MAIL_INSPECTION_TYPE_UNAVAILABLE,
    ADMIN_MAIL_INSPECTION_UNAVAILABLE,
    ADMIN_INFRASTRUCTURE_UNAVAILABLE
}
