package com.example.temperate.service.user.aiconversation.exception;

/**
 * 定义 AI 会话生成、上下文、额度和上游流式调用可安全暴露的受控错误码。
 */
public enum AiConversationErrorCode {
    AI_REQUEST_INVALID,
    AI_ATTACHMENT_INVALID,
    AI_ATTACHMENT_STORAGE_UNAVAILABLE,
    AI_ATTACHMENT_CAPABILITY_UNSUPPORTED,
    AI_MODEL_NOT_AVAILABLE,
    AI_MODEL_LIMITS_MISSING,
    AI_CONVERSATION_NOT_FOUND,
    AI_CONVERSATION_BUSY,
    AI_CONCURRENCY_LIMIT_REACHED,
    AI_IDEMPOTENCY_CONFLICT,
    AI_QUOTA_INSUFFICIENT,
    AI_QUOTA_RULE_MISSING,
    AI_CONTEXT_TOO_LARGE,
    AI_CONTEXT_COMPACTION_FAILED,
    AI_UPSTREAM_UNAVAILABLE,
    AI_UPSTREAM_TIMEOUT,
    AI_UPSTREAM_STREAM_FAILED,
    AI_MODEL_REASONING_LEVEL_UNSUPPORTED,
    AI_IMAGE_RESOLUTION_UNSUPPORTED,
    AI_PROVIDER_TOOL_UNSUPPORTED,
    AI_USAGE_UNAVAILABLE,
    AI_SETTLEMENT_RECONCILE_REQUIRED,
    AI_CONTEXT_CACHE_UNAVAILABLE,
    AI_RUNTIME_LINKAGE_FAILED
}
