package com.example.temperate.service.admin.mailinspection.domain;

/**
 * 定义邮箱检查输入、OAuth、IMAP 与业务证据分类的全部稳定结果码。
 */
public enum MailInspectionResultStatus {
    INVALID_CREDENTIAL_FORMAT,
    INVALID_EMAIL,
    INVALID_PASSWORD_FIELD,
    INVALID_CLIENT_ID,
    INVALID_REFRESH_TOKEN,
    DUPLICATE_EMAIL,

    REFRESH_TOKEN_EXPIRED,
    REFRESH_TOKEN_REVOKED,
    OAUTH_AUTHORIZATION_FAILED,
    OAUTH_CLIENT_INVALID,
    OAUTH_CLIENT_TOKEN_MISMATCH,
    OAUTH_CONSENT_REQUIRED,
    MICROSOFT_ACCOUNT_RESTRICTED,
    OAUTH_RATE_LIMIT_EXHAUSTED,
    OAUTH_TRANSIENT_EXHAUSTED,
    OAUTH_NETWORK_EXHAUSTED,
    OAUTH_RESPONSE_INVALID,

    IMAP_AUTHENTICATION_FAILED,
    IMAP_ACCESS_DENIED,
    IMAP_MAILBOX_UNAVAILABLE,
    IMAP_NETWORK_EXHAUSTED,
    IMAP_TRANSIENT_EXHAUSTED,
    IMAP_SCAN_TIMEOUT,

    OPENAI_NO_REGISTRATION_EVIDENCE,
    OPENAI_REGISTERED_NORMAL,
    OPENAI_RESTRICTED_EVIDENCE_FOUND,
    OPENAI_UNCLASSIFIED,

    KIRO_NO_REGISTRATION_EVIDENCE,
    KIRO_REGISTERED_NORMAL,
    KIRO_RESTRICTED_EVIDENCE_FOUND,
    KIRO_UNCLASSIFIED,

    IP2_REGISTRATION_MAIL_FOUND,
    IP2_REGISTRATION_MAIL_NOT_FOUND,
    IP2_VERIFY_URL_FOUND,
    IP2_VERIFY_URL_NOT_FOUND,
    IP2_VERIFY_URL_MALFORMED,

    RABBIT_DISPATCH_EXHAUSTED,
    INTERNAL_PROCESSING_FAILURE
}
