package com.example.temperate.service.auth.passwordreset;

/**
 * 枚举密码重置流程向传输层暴露的稳定业务错误码。
 */
public enum PasswordResetErrorCode {
    INVALID_INPUT,
    PASSWORD_STRENGTH_INSUFFICIENT,
    RESET_FLOW_NOT_FOUND,
    RESET_FLOW_EXPIRED,
    RESET_FLOW_FORBIDDEN,
    HUMAN_VERIFICATION_REQUIRED,
    TURNSTILE_REJECTED,
    VERIFICATION_COOLDOWN,
    VERIFICATION_SEND_LIMIT,
    VERIFICATION_CODE_EXPIRED,
    VERIFICATION_CODE_INVALID,
    RESET_BLOCKED,
    FORGET_TOKEN_INVALID,
    SESSION_REVOCATION_FAILED,
    INFRASTRUCTURE_UNAVAILABLE
}
