package com.example.temperate.service.admin.aimodel.icon;

/**
 * 定义管理员模型图标接口可以安全映射到 HTTP 响应的稳定业务错误码。
 */
public enum AiModelIconErrorCode {
    AI_MODEL_ICON_INPUT_INVALID,
    AI_MODEL_ICON_PUBLIC_ID_INVALID,
    AI_MODEL_ICON_NOT_FOUND,
    AI_MODEL_ICON_NAME_CONFLICT,
    AI_MODEL_ICON_OBJECT_CONFLICT,
    AI_MODEL_ICON_IN_USE,
    AI_MODEL_ICON_IMAGE_INVALID,
    AI_MODEL_ICON_IMAGE_FORMAT_UNSUPPORTED,
    AI_MODEL_ICON_IMAGE_UNSAFE,
    AI_MODEL_ICON_DECODER_UNAVAILABLE,
    AI_MODEL_ICON_FILE_TOO_LARGE,
    AI_MODEL_ICON_REMOTE_URL_INVALID,
    AI_MODEL_ICON_REMOTE_DNS_RESOLUTION_FAILED,
    AI_MODEL_ICON_REMOTE_HOST_NOT_PUBLIC,
    AI_MODEL_ICON_REMOTE_CONNECT_FAILED,
    AI_MODEL_ICON_REMOTE_CONNECT_TIMEOUT,
    AI_MODEL_ICON_REMOTE_READ_TIMEOUT,
    AI_MODEL_ICON_REMOTE_TLS_HANDSHAKE_FAILED,
    AI_MODEL_ICON_REMOTE_REDIRECT_INVALID,
    AI_MODEL_ICON_REMOTE_HTTP_STATUS_INVALID,
    AI_MODEL_ICON_REMOTE_RESPONSE_TOO_LARGE,
    AI_MODEL_ICON_REMOTE_RESPONSE_INVALID,
    AI_MODEL_ICON_STORAGE_UNAVAILABLE
}
