const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')
const test = require('node:test')

const frontendRoot = path.resolve(__dirname, '../..')

function read(relativePath) {
	return fs.readFileSync(path.join(frontendRoot, relativePath), 'utf8')
}

function parseUniPages(source) {
	return JSON.parse(source.replace(/^\s*\/\/\s*#(?:ifn?def|endif).*$/gm, ''))
}

test('chat page creates a conversation only on first send and refreshes the sidebar only after completed', () => {
	const entry = read('pages/ai-chat/index.vue')
	const page = read('components/user/workspace/user-chat-panel.vue')
	const workspace = read('components/user/user-workspace.vue')
	const pages = parseUniPages(read('pages.json'))
	const route = pages.pages.find(item => item.path === 'pages/ai-chat/index')

	assert.match(entry, /<user-workspace[\s\S]*initial-destination="chat"/)
	assert.equal(route?.style?.navigationStyle, 'custom')
	assert.match(page, /newChat\(\)[\s\S]*resetCurrentConversation\(\)/)
	assert.doesNotMatch(page, /newChat\(\)[\s\S]{0,300}aiConversationApi\./)
	assert.match(page, /event\.type === 'accepted'[\s\S]*setAcceptedConversation/)
	assert.match(page, /event\.type === 'completed'[\s\S]*\$emit\('conversation-completed'\)/)
	assert.match(workspace, /@conversation-completed="refreshConversations"/)
	assert.match(page, /Idempotency-Key|idempotencyKey/)
	assert.match(page, /this\.activeStream\?\.close/)
})

test('chat page sends and remembers the provider-specific reasoning effort', () => {
	const page = read('components/user/workspace/user-chat-panel.vue')
	const modelLevels = read('common/aichat/ai-conversation-model-levels.js')

	assert.match(page, /REASONING_EFFORT_STORAGE_KEY/)
	assert.match(page, /aiConversationModelLevelOptions/)
	assert.match(modelLevels, /anthropic:[\s\S]*XHigh[\s\S]*Max/)
	assert.match(modelLevels, /google:[\s\S]*Minimal[\s\S]*Low[\s\S]*Medium[\s\S]*High/)
	assert.match(page, /selectedReasoningEffortLevel:\s*2/)
	assert.match(page, /supportedReasoningEffortLevels/)
	assert.match(page, /defaultReasoningEffortLevel/)
	assert.match(page, /@change="selectReasoningEffort"/)
	assert.match(page, /uni\.getStorageSync\(REASONING_EFFORT_STORAGE_KEY\)/)
	assert.match(page, /uni\.setStorageSync\(REASONING_EFFORT_STORAGE_KEY,\s*level\)/)
	assert.match(page, /reasoningEffortLevel:\s*this\.selectedReasoningEffortLevel/)
	assert.match(page, /:disabled="generating \|\| !selectedModel"/)
	assert.match(page, /selectModel\(event\)[\s\S]*normalizeReasoningEffortForModel/)
})

test('image generation accepts the Google fourth tier and always disables web search', () => {
	const page = read('components/user/workspace/user-chat-panel.vue')
	const image = read('common/aichat/ai-conversation-image-generation.js')
	const webSearch = read('common/aichat/ai-conversation-web-search.js')

	assert.match(image, /level <= 4/)
	assert.match(webSearch, /!capabilities\.has\('IMAGE_GENERATION'\)/)
	assert.match(page,
		/const webSearchMode = this\.imageGenerationAvailable[\s\S]*AI_CONVERSATION_WEB_SEARCH_MODES\.OFF[\s\S]*normalizeAiConversationWebSearchMode/)
	assert.match(page, /profileControlLabel\(\)[\s\S]*'画质'/)
})

test('multi image controls use capability checks, one downstream stream and bounded slots', () => {
	const page = read('components/user/workspace/user-chat-panel.vue')
	const image = read('common/aichat/ai-conversation-image-generation.js')
	const stream = read('common/aichat/ai-conversation-stream.js')
	const dialog = read('components/user/workspace/user-image-output-count-dialog.vue')

	assert.match(image, /capabilities\.has\('IMAGE_GENERATION'\)[\s\S]*capabilities\.has\('IMAGE_EDIT'\)/)
	assert.doesNotMatch(image, /gpt-image-2|gpt-image-1\.5/)
	assert.match(page, /数量 · \{\{ selectedImageOutputCount \}\}/)
	assert.doesNotMatch(page, /createImageOutputSlots\(requestedImageCount\)/)
	assert.match(page, /generatedImageGallery\(message\)/)
	assert.match(page, /imagePresentationOrder:\s*\[\]/)
	assert.match(page, /imageGenerationRequest\([\s\S]{0,180}requestedImageCount/)
	assert.match(dialog, /maxlength="2"/)
	assert.match(dialog, /parseImageOutputCount/)
	assert.match(stream, /previewImages:\s*mergeImagePreviewOutput/)
	assert.match(stream, /image-output-status/)
	assert.match(stream, /requestedImageCount/)
	assert.match(page, /messagePublicId: event\.data\?\.messagePublicId/)
	assert.match(page, /if \(!requestedImageCount\) this\.reloadCurrentMessages\(\)/)
	assert.equal((stream.match(/openGenerationOnce\(/g) || []).length >= 1, true)
})

test('generated response images use stable two-primary layouts and a conversation viewer without changing uploads', () => {
	const page = read('components/user/workspace/user-chat-panel.vue')
	const gallery = read('components/user/workspace/user-generated-image-gallery.vue')
	const viewer = read('components/user/workspace/user-generated-image-viewer.vue')

	assert.match(page,
		/message\.contentAttachments\?\.length[\s\S]*?<!-- #ifndef APP-PLUS -->\s*<image[^>]*class="attachment-image"[^>]*mode="aspectFill"/)
	assert.match(page, /<user-generated-image-gallery/)
	assert.match(page, /:presentation="generatedImageGallery\(message\)"/)
	assert.match(page, /@open="openGeneratedImageViewer"/)
	assert.match(page, /<user-generated-image-viewer/)
	assert.match(gallery, /generated-image-progress/)
	assert.match(gallery, /presentation\.allItems/)
	assert.match(gallery, /presentation\?\.primaryItems/)
	assert.match(gallery, /presentation\?\.visibleSecondaryItems/)
	assert.match(gallery, /DUAL_WITH_RAIL:\s*'is-dual-with-rail'/)
	assert.match(gallery, /class="generated-image-more"/)
	assert.match(gallery, /openOverflow\(\)[\s\S]*?secondaryItems/)
	assert.match(gallery, /width:\s*min\(100%,\s*720px\)/)
	assert.match(page, /\.attachment-image\s*\{[^}]*height:\s*180px/)
	assert.match(gallery, /\.generated-image-stage\.is-hero-two/)
	assert.match(gallery, /\.generated-image-stage\.is-hero-three/)
	assert.match(gallery, /@keyframes generated-image-gallery-exit/)
	assert.match(viewer, /role="dialog"/)
	assert.match(viewer, /mode="aspectFit"/)
	assert.match(viewer, /\$emit\('request-older'\)/)
	assert.match(viewer, /\$emit\('download', activeItem\)/)
	assert.doesNotMatch(page, /urls:\s*\[source\]/)
})

test('H5 chat uses one collapsible conversation sidebar and a progressive settings surface', () => {
	const workspace = read('components/user/user-workspace.vue')
	const sidebar = read('components/user/user-h5-workspace-sidebar.vue')
	const chatPanel = read('components/user/workspace/user-chat-panel.vue')
	const settings = read('components/user/workspace/user-h5-generation-settings.vue')

	assert.equal((workspace.match(/<user-workspace-sidebar\b/g) || []).length, 1)
	assert.match(sidebar, /workspace-sidebar-header/)
	assert.match(sidebar, /workspace-sidebar-footer/)
	assert.match(chatPanel,
		/\.chat-main\s*\{[^}]*grid-template-columns:\s*minmax\(0,\s*1fr\)/)
	assert.match(chatPanel, /class="generation-settings-trigger"/)
	assert.match(chatPanel, /:aria-expanded="String\(generationSettingsOpen\)"/)
	assert.match(chatPanel, /<user-h5-generation-settings/)
	assert.match(chatPanel, /generationSettingsPresentation/)
	assert.match(settings, /@keydown\.esc\.stop\.prevent="requestClose"/)
	assert.match(settings, /@keydown\.tab="trapFocus"/)
	assert.match(settings, /h5-generation-settings-surface-motion-enter-active/)
	assert.match(settings, /h5-generation-settings-surface-motion-leave-active/)
	assert.match(chatPanel, /this\.\$refs\.generationSettingsTrigger/)
})

test('H5 workspace restructuring leaves the Android navigation and generation state isolated', () => {
	const workspace = read('components/user/user-workspace.vue')
	const panel = read('components/user/workspace/user-chat-panel.vue')

	assert.match(workspace, /let recentExpanded = false[\s\S]*#ifdef H5[\s\S]*recentExpanded = true/)
	assert.match(workspace, /#ifndef H5[\s\S]*<user-workspace-sidebar/)
	assert.match(panel, /#ifndef H5[\s\S]*class="icon-button mobile-only"/)
	assert.match(panel, /<user-android-chat-settings-sheet[\s\S]*v-if="androidClient"/)
	assert.doesNotMatch(panel, /androidGenerationSettingsExpanded|toggleAndroidGenerationSettings/)
	assert.match(panel, /#ifdef H5[\s\S]*class="generation-settings-trigger"[\s\S]*#endif[\s\S]*<user-model-selector/)
})

test('recent conversations are expanded in the focused sidebar and loaded on demand', () => {
	const page = read('components/user/user-workspace.vue')
	const sidebar = read('components/user/user-h5-workspace-sidebar.vue')
	const recent = read('components/user/user-recent-conversations.vue')
	const recentUsages = sidebar.match(/<user-recent-conversations\b/g) || []

	assert.match(page, /let recentExpanded = false[\s\S]*#ifdef H5[\s\S]*recentExpanded = true/)
	assert.doesNotMatch(page, /onAuthenticatedPageReady\(\)[\s\S]{0,180}refreshConversations\(\)/)
	assert.match(page, /ensureRecentConversations\(\)[\s\S]*this\.conversationsLoaded/)
	assert.match(page, /toggleRecentConversations\(\)[\s\S]*this\.recentExpanded = !this\.recentExpanded[\s\S]*ensureRecentConversations\(\)/)
	assert.match(page, /sidebarPreferenceTouched:\s*false/)
	assert.match(page, /handleWorkspaceResize/)
	assert.equal(recentUsages.length, 1)
	assert.match(recent, /:aria-expanded="String\(expanded\)"/)
	assert.match(recent, /:aria-controls="contentId"/)
	assert.match(recent, /:id="contentId"/)
	assert.match(recent, /v-if="expanded"/)
})

test('conversation public IDs are never rendered as body text and copy through the platform clipboard', () => {
	const page = read('components/user/user-workspace.vue')
	const recent = read('components/user/user-recent-conversations.vue')

	assert.doesNotMatch(recent, /\{\{\s*conversation\.conversationPublicId\s*\}\}/)
	assert.match(recent, /class="conversation-open"/)
	assert.match(recent, /class="conversation-copy"/)
	assert.doesNotMatch(recent, /<button[^>]*class="conversation-open"(?:(?!<\/button>)[\s\S])*<button/)
	assert.match(page, /copyConversationId\(conversationPublicId\)[\s\S]*uni\.setClipboardData\([\s\S]*data:\s*conversationPublicId/)
	assert.match(page, /会话 ID 已复制/)
	assert.doesNotMatch(page, /setStorageSync\([^)]*conversation/i)
})

test('chat page supports generic attachments while only media categories require model capabilities', () => {
	const page = read('components/user/workspace/user-chat-panel.vue')
	const cards = read('components/user/workspace/user-chat-attachment-list.vue')
	const upload = read('common/aichat/ai-conversation-upload.js')
	const state = read('common/aichat/ai-conversation-upload-state.js')
	const picker = read('common/aichat/ai-conversation-file-picker.js')
	const androidPicker = read('uni_modules/ait-document-picker/utssdk/app-android/index.uts')
	const androidUpload = read('uni_modules/ait-oss-put/utssdk/app-android/index.uts')

	assert.match(page, /chooseConversationFiles/)
	assert.match(picker, /uni\.chooseFile/)
	assert.match(picker, /chooseDocuments/)
	assert.match(androidPicker, /Intent\.ACTION_OPEN_DOCUMENT/)
	assert.match(androidPicker, /intent\.setType\('\*\/\*'\)/)
	assert.match(state, /if \(category === 'IMAGE'\) return 'IMAGE_INPUT'/)
	assert.match(state, /if \(category === 'AUDIO'\) return 'AUDIO_INPUT'/)
	assert.match(state, /if \(category === 'VIDEO'\) return 'VIDEO_INPUT'/)
	assert.match(state, /if \(!required \|\| !model\) return true/)
	assert.match(page, /image\/svg\+xml/)
	assert.match(cards, /image\/svg\+xml/)
	assert.match(upload, /MAX_CONCURRENCY = 3/)
	assert.match(upload, /MAX_FILE_BYTES = 100 \* 1024 \* 1024/)
	assert.match(upload, /MAX_TOTAL_BYTES = 200 \* 1024 \* 1024/)
	assert.match(upload, /AI_ATTACHMENT_TOTAL_SIZE_EXCEEDED/)
	assert.match(upload, /XMLHttpRequest/)
	assert.match(upload, /request\.upload\.onprogress/)
	assert.match(upload, /content-length/)
	assert.match(upload, /putFile/)
	assert.match(upload, /connection\?\.close/)
	assert.match(upload, /request\?\.abort/)
	assert.match(upload, /isRetryableUploadFailure/)
	assert.match(upload, /createPreuploads\(\[job\.declared\]\)/)
	assert.match(androidUpload, /setFixedLengthStreamingMode/)
	assert.match(androidUpload, /name\.lowercase\(\) == 'content-length'/)
	assert.doesNotMatch(upload, /authorizedRequest\([^)]*uploadUrl/)
	assert.match(page, /validateAttachmentSelection\(this\.pendingAttachments, selected\)/)
	assert.match(page, /this\.startAttachmentBatch\(files\)/)
	assert.match(page, /removed\.uploadTask\?\.cancel/)
	assert.match(page, /this\.cancelPendingUploads\(\)/)
	assert.match(page, /URL\?\.revokeObjectURL/)
	assert.match(page, /event\.type === 'completed'[\s\S]*releasePreviewUrls/)
	assert.match(cards, /pending-progress-ring/)
	assert.match(cards, /不受当前模型支持/)
})

test('Android document picker uses UTS-compatible expressions instead of Kotlin-only syntax', () => {
	const androidPicker = read('uni_modules/ait-document-picker/utssdk/app-android/index.uts')

	assert.doesNotMatch(androidPicker, /-?\d+L\b/)
	assert.doesNotMatch(androidPicker, /\s\?:\s/)
	assert.doesNotMatch(androidPicker, /\buntil\b/)
	assert.match(androidPicker, /const REQUEST_CODE: Int = 17341/)
	assert.match(androidPicker, /const input = resolver\.openInputStream\(uri\)[\s\S]{0,120}if \(input == null\)/)
	assert.match(androidPicker, /const limit: Int = Math\.min\(count, clipData\.getItemCount\(\)\)\.toInt\(\)/)
	assert.match(androidPicker, /for \(let index: Int = 0; index < limit; index\+\+\)/)
	assert.match(androidPicker, /selected\.forEach\(\(uri: Uri\) => \{[\s\S]{0,100}files\.add\(copyUri\(uri\)\)/)
	assert.doesNotMatch(androidPicker, /selected\.forEach\(\(uri: Uri\) => files\.add/)
	assert.match(androidPicker, /const errorMessage = error\.message/)
	assert.doesNotMatch(androidPicker, /error\.getMessage\(\)/)
})

test('Android UTS HTTP plugins use Int lengths and key-only UTSJSONObject iteration', () => {
	const androidUpload = read('uni_modules/ait-oss-put/utssdk/app-android/index.uts')
	const androidSse = read('uni_modules/ait-sse/utssdk/app-android/index.uts')

	assert.match(androidUpload, /setFixedLengthStreamingMode\(options\.sizeBytes\.toInt\(\)\)/)
	assert.match(androidUpload, /options\.headers\.forEach\(\(name: string\) => \{/)
	assert.match(androidUpload, /const value = options\.headers\[name\]/)
	assert.doesNotMatch(androidUpload, /headers\.forEach\(\(value:[^,]+,\s*name:/)
	assert.match(androidSse, /options\.headers\.forEach\(\(name: string\) => \{/)
	assert.match(androidSse, /const value = options\.headers\[name\]/)
	assert.doesNotMatch(androidSse, /headers\.forEach\(\(value:[^,]+,\s*name:/)
})

test('audio attachments use the generic cross-platform open flow', () => {
	const page = read('components/user/workspace/user-chat-panel.vue')
	const state = read('common/aichat/ai-conversation-upload-state.js')

	assert.doesNotMatch(page, /<audio\b/)
	assert.doesNotMatch(page, /previewAudio/)
	assert.match(page, /openAttachment\(attachment\)/)
	assert.match(page, /window\.open\(attachment\.url, '_blank', 'noopener,noreferrer'\)/)
	assert.match(page, /plus\.runtime\.openURL\(attachment\.url\)/)
	assert.match(page, /createOptimisticInputPresentation\(/)
	assert.match(page, /contentAttachments: inputPresentation\.attachments/)
	assert.match(state, /const category = attachmentCategory\(file\)/)
})

test('attachments preupload immediately and gate sending until every file is ready', () => {
	const page = read('components/user/workspace/user-chat-panel.vue')
	const state = read('common/aichat/ai-conversation-upload-state.js')

	assert.match(page, /createPendingAttachment\(file, uuidV4\(\)\)/)
	assert.match(page, /startAttachmentBatch\(files\)/)
	assert.doesNotMatch(page, /ensureUploaded/)
	assert.match(page, /const attachmentRefs = selectedAttachments\.map\(file => file\.uploaded\)/)
	assert.match(state, /PREPARING[\s\S]*UPLOADING[\s\S]*UPLOADED[\s\S]*FAILED/)
	assert.match(state, /state !== ATTACHMENT_UPLOAD_STATES\.UPLOADED/)
	assert.match(state, /!isAttachmentCompatible\(file, model\)/)
	assert.match(page, /:disabled="!canSend"/)
	assert.match(page, /sendBlockedReason/)
})

test('finalization uses the activity event while showing attachment persistence progress', () => {
	const page = read('components/user/workspace/user-chat-panel.vue')

	assert.match(page, /event\.type === 'activity'/)
	assert.match(page, /activity\.phase === 'FINALIZING'/)
	assert.match(page, /saving:\s*true/)
	assert.match(page, /正在保存生成内容/)
	assert.match(page, /ATTACHMENT_STORAGE_PARTIAL/)
})

test('web search is capability gated and research events remain in session storage', () => {
	const page = read('components/user/workspace/user-chat-panel.vue')
	const capability = read('common/aichat/ai-conversation-web-search.js')
	const research = read('common/aichat/ai-conversation-research-session.js')

	assert.match(capability, /capabilities\.has\('RESPONSES'\)/)
	assert.match(capability, /capabilities\.has\('WEB_SEARCH'\)/)
	assert.match(page, /webSearchMode,/)
	assert.match(page, /AI_CONVERSATION_WEB_SEARCH_OPTIONS/)
	assert.match(page, /@change="handleGenerationSettingsChange"/)
	assert.match(page, /AI_CONVERSATION_WEB_SEARCH_MODES\.OFF/)
	assert.match(page, /generationSettingsSections\(\)[\s\S]*'webSearch'/)
	assert.match(page, /<user-h5-generation-settings[\s\S]*:sections="generationSettingsSections"/)
	assert.match(page, /webSearchActive\(\)[\s\S]*selectedWebSearchMode !== AI_CONVERSATION_WEB_SEARCH_MODES\.OFF/)
	assert.match(page,
		/const option = this\.webSearchOptions\[Number\(event\.detail\.value\)\][\s\S]*if \(this\.androidClient\) this\.preferredWebSearchMode = option\.value[\s\S]*selectedWebSearchMode = normalizeAiConversationWebSearchMode/)
	assert.match(page, /event\.type === 'activity'/)
	assert.match(page, /event\.type === 'source'/)
	assert.match(page, /event\.type === 'reasoning_summary'/)
	assert.match(page, /requestAnimationFrame|createAiConversationTextDrain/)
	assert.match(research, /globalThis\.sessionStorage/)
	assert.match(research, /MAX_STORAGE_BYTES = 2 \* 1024 \* 1024/)
	assert.match(research, /MAX_RECORDS = 20/)
	assert.match(research, /activityEventKeys/)
	assert.match(page, /eventId: String\(value\?\.eventId \|\| ''\)/)
	assert.match(page, /if \(activityAccepted === false\) return/)
	assert.match(page, /item\?\.activity\?\.eventId \|\| `activity-\$\{item\?\.sequence\}`/)
	assert.match(page, /STARTED:\s*'已开始'/)
	assert.match(page, /IN_PROGRESS:\s*'进行中'/)
	assert.match(page, /COMPLETED:\s*'已完成'/)
	assert.match(page, /FAILED:\s*'失败'/)
	assert.match(page, /UNAVAILABLE:\s*'不可用'/)
	assert.doesNotMatch(research, /localStorage/)
})

test('history reopening never merges Redis interrupted output into the visible timeline', () => {
	const page = read('components/user/workspace/user-chat-panel.vue')
	const api = read('common/aichat/ai-conversation-api.js')
	const store = read('common/aichat/ai-conversation-store.js')

	assert.match(page, /aiConversationApi\.messages/)
	assert.match(page, /discardTransientMessages/)
	assert.match(page, /markAiConversationHistoryStale/)
	assert.match(page, /resyncStaleHistory/)
	assert.match(page, /clearAiConversationHistoryStale/)
	assert.match(store, /filter\(message => Boolean\(message\.messagePublicId\)\)/)
	assert.doesNotMatch(api, /Redis|ephemeral/)
})

test('research recovery binds stored process to its exact persisted message', () => {
	const page = read('components/user/workspace/user-chat-panel.vue')
	const research = read('common/aichat/ai-conversation-research-session.js')

	assert.match(page, /bindMessage\?\.\(\s*event\.data\?\.messagePublicId/)
	assert.match(page, /messagePublicId:\s*message\.messagePublicId/)
	assert.doesNotMatch(page, /patchLatestMessage/)
	assert.match(research, /if \(messagePublicId != null\)/)
})

test('H5 and Android share one SSE parser and Android transport accepts POST JSON plus cancellation', () => {
	const h5 = read('common/aichat/ai-conversation-sse-h5.js')
	const android = read('common/aichat/ai-conversation-sse-app.js')
	const stream = read('common/aichat/ai-conversation-stream.js')
	const page = read('components/user/workspace/user-chat-panel.vue')
	const errorPresentation = read('common/aichat/ai-conversation-error-presentation.js')
	const uts = read('uni_modules/ait-sse/utssdk/interface.uts')
	const androidTransport = read('uni_modules/ait-sse/utssdk/app-android/index.uts')

	assert.match(h5, /createAiConversationSseParser/)
	assert.match(h5, /MAX_ERROR_BYTES = 16 \* 1024/)
	assert.match(h5, /boundedResponseText\(response\)[\s\S]*JSON\.parse/)
	assert.match(h5, /while \(total < MAX_ERROR_BYTES\)/)
	assert.match(h5, /error\.code = payload\?\.code/)
	assert.match(h5, /error\.statusCode = response\.status/)
	assert.match(android, /createAiConversationSseParser/)
	assert.match(android, /terminalReceived/)
	assert.match(android, /CLIENT_RESPONSE_HEADERS/)
	assert.match(
		androidTransport,
		/@UTSJS\.keepAlive\s+export function openSseRequest/
	)
	assert.match(androidTransport, /MAX_ERROR_BODY_BYTES = 16 \* 1024/)
	assert.match(androidTransport, /getErrorStream\(\)/)
	assert.match(androidTransport, /JSON\.parse\(body\)/)
	assert.match(androidTransport, /createFailure\(/)
	assert.match(androidTransport, /exceptionType/)
	assert.match(androidTransport, /closedByCaller/)
	assert.match(
		androidTransport,
		/getHeaderField\('Content-Type'\)[\s\S]*text\/event-stream/
	)
	assert.match(stream, /Accept:\s*'text\/event-stream, application\/json'/)
	assert.match(stream, /if \(closed\) \{\s*active\.close\?\.\(closeReason, closeDetails\)\s*return\s*\}/)
	assert.match(android, /lifecycleDiagnostics\?\.stopRequested\?\.\(reason, details\)/)
	assert.match(android, /lifecycleDiagnostics\?\.abortCalled\?\.\(\)/)
	assert.match(errorPresentation, /AI_QUOTA_INSUFFICIENT:\s*'额度不足，请充值。'/)
	assert.match(page, /aiConversationErrorMessage\(error\)/)
	assert.match(page, /aiConversationErrorMessage\(\s*event\.data,\s*'模型响应未能完成'\s*\)/)
	assert.match(page, /error:\s*message/)
	assert.match(page, /this\.composerError = message/)
	assert.match(uts, /method:\s*string/)
	assert.match(uts, /body:\s*string/)
	assert.match(uts, /close:\s*\(callerInitiated:\s*boolean\) => void/)
})

test('stream diagnostics connect browser reads, parsed SSE and rendered text without logging content', () => {
	const stream = read('common/aichat/ai-conversation-stream.js')
	const h5 = read('common/aichat/ai-conversation-sse-h5.js')
	const android = read('common/aichat/ai-conversation-sse-app.js')
	const panel = read('components/user/workspace/user-chat-panel.vue')
	const diagnostics = read('common/aichat/ai-conversation-stream-diagnostics.js')

	assert.match(h5, /BROWSER_READ/)
	assert.match(android, /BROWSER_READ/)
	assert.match(stream, /BROWSER_SSE_PARSED/)
	assert.match(stream, /sequence: event\.data\?\.sequence/)
	assert.match(panel, /FRONTEND_RENDERED/)
	assert.match(panel, /recordResearchRendered\('activity'\)/)
	assert.match(panel, /recordResearchRendered\('source'\)/)
	assert.match(panel, /recordResearchRendered\('reasoning_summary'\)/)
	assert.doesNotMatch(
		`${stream}\n${panel}`,
		/enabled:\s*clientPlatform\(\) === 'H5' \? undefined : false/
	)
	assert.match(`${stream}\n${panel}`, /clientPlatform\(\) === 'ANDROID' \? true : undefined/)
	assert.match(diagnostics, /ai_stream_client_timing_summary/)
	assert.doesNotMatch(diagnostics, /event\.data\.text/)
	assert.doesNotMatch(diagnostics, /console\.log/)
})

test('H5 streaming follows only near the bottom and exposes a return-to-latest action', () => {
	const panel = read('components/user/workspace/user-chat-panel.vue')

	assert.match(panel, /H5_TURN_FOLLOW_LATEST_PX\s*=\s*H5_FOLLOW_LATEST_MAX_DISTANCE/)
	assert.match(panel, /TURN_FOLLOW_LATEST_PX\s*=\s*320/)
	assert.match(panel, /class="return-latest"/)
	assert.match(panel, /v-if="!turnFollowLatest && messages\.length"/)
	assert.match(panel, /resumeFollowingLatest\(\)/)
	assert.match(panel, /resolveH5FollowLatest\(\{[\s\S]*previousScrollTop[\s\S]*nextScrollTop/)
	assert.match(panel, /clientPlatform\(\) === 'H5' && !force && !this\.turnFollowLatest/)
})

test('H5 content, toolbar, and composer fill the remaining-workspace axis', () => {
	const panel = read('components/user/workspace/user-chat-panel.vue')

	assert.match(panel, /\.chat-main\s*\{[^}]*grid-template-rows:\s*auto minmax\(0,\s*1fr\) auto/)
	assert.match(panel,
		/\.chat-main:not\(\.is-android-client\) \.message-shell\s*\{[^}]*width:\s*100%[^}]*max-width:\s*none/)
	assert.match(panel,
		/\.chat-main:not\(\.is-android-client\) \.composer-wrap\s*\{[^}]*width:\s*100%[^}]*max-width:\s*none/)
	assert.match(panel, /padding:\s*32px clamp\(16px,\s*3vw,\s*32px\) 32px/)
	assert.match(panel, /\.message-block\s*\{[^}]*max-width:\s*78%/)
	assert.match(panel, /\.message-text\s*\{[^}]*font-size:\s*16px[^}]*line-height:\s*1\.68/)
	assert.match(panel, /\.composer-input\s*\{[^}]*max-height:\s*160px/)
	assert.match(panel, /\.chat-main:not\(\.is-android-client\) \.composer-input\s*\{[^}]*overflow-y:\s*auto/)
})

test('desktop chat renders a bounded Codex turn rail instead of every cached message', () => {
	const panel = read('components/user/workspace/user-chat-panel.vue')
	const rail = read('components/user/workspace/user-conversation-turn-rail.vue')
	const navigation = read('common/aichat/ai-conversation-turn-navigation.js')

	assert.match(panel, /<user-conversation-turn-rail/)
	assert.match(panel, /v-for="\(message, renderedIndex\) in renderedMessages"/)
	assert.match(panel, /:key="messageElementId\(message, renderedMessageIndex\(renderedIndex\)\)"/)
	assert.doesNotMatch(panel, /:key="messageTurnKey\(/)
	assert.doesNotMatch(panel, /v-for="message in messages"/)
	assert.doesNotMatch(panel, /turn-window-spacer/)
	assert.doesNotMatch(panel, /topTurnSpacerHeight|bottomTurnSpacerHeight/)
	assert.doesNotMatch(panel, /ResizeObserver|estimateTurnHeight|sumTurnHeights/)
	assert.match(panel, /@scroll="handleMessageScroll"/)
	assert.match(panel, /:scroll-into-view="turnNavigationDesktop \? '' : scrollTarget"/)
	assert.match(panel, /resolveTurnScrollElement\(/)
	assert.match(panel, /setDesktopScrollTop\(/)
	assert.equal((panel.match(/\.scrollTop\s*=/g) || []).length, 1)
	assert.match(panel, /TURN_WINDOW_SIZE\s*=\s*50/)
	assert.match(panel, /TURN_WINDOW_SHIFT\s*=\s*25/)
	assert.match(panel, /loadOlderMessages\(\{ preserveAnchor: true \}\)/)
	assert.match(panel, /scrollBottom\(\{ force: true \}\)/)
	assert.match(panel, /:positions-known="!hasMoreMessages"/)

	assert.match(rail,
		/\.conversation-turn-rail\s*\{[^}]*position:\s*absolute[^}]*left:\s*0/)
	assert.doesNotMatch(rail, /left:\s*calc\(50%\s*-\s*\d+px\)/)
	assert.doesNotMatch(panel, /padding-left:\s*62px/)
	assert.match(rail, /role="navigation"/)
	assert.match(rail, /aria-label="当前会话轮次"/)
	assert.match(rail, /aria-current/)
	assert.match(rail, /'is-active': turn\.key === activeTurnKey/)
	assert.match(rail, /'is-previewed': index === previewIndex/)
	assert.match(rail, /:style="markerLineStyle\(index\)"/)
	assert.match(rail, /@click="selectMarker\(turn, index\)"/)
	assert.match(rail, /markerLineStyle\(index\)[\s\S]{0,160}turnMarkerWidth\(index, this\.previewIndex\)/)
	assert.doesNotMatch(rail, /is-\$\{turn\.status\}/)
	assert.match(rail,
		/\.turn-marker-button\.is-active \.turn-marker-line\s*\{[^}]*background:\s*#8fdcbe/)
	assert.doesNotMatch(rail,
		/\.turn-marker-button\.is-active \.turn-marker-line\s*\{[^}]*width:/)
	assert.match(rail,
		/\.turn-marker-button\.is-previewed:not\(\.is-active\) \.turn-marker-line\s*\{[^}]*background:/)
	assert.doesNotMatch(rail,
		/\.turn-marker-button\.is-(?:streaming|saving|stopped|failed) \.turn-marker-line/)
	assert.doesNotMatch(rail, /turn-marker-pulse/)
	assert.match(rail, /ArrowUp/)
	assert.match(rail, /ArrowDown/)
	assert.match(rail, /Home/)
	assert.match(rail, /End/)
	assert.match(rail, /<button[\s\S]{0,180}v-if="previewTurn"[\s\S]{0,300}class="turn-preview-card"/)
	assert.match(rail, /class="turn-preview-card"[\s\S]{0,300}@click="selectPreviewTurn"/)
	assert.doesNotMatch(rail, /turn-preview-jump|跳转到完整问答/)
	assert.match(rail, /width:\s*min\(288px,/)
	assert.match(rail, /max-height:\s*176px/)
	assert.match(rail, /prefers-reduced-motion:\s*reduce/)
	assert.match(rail, /@media screen and \(max-width:\s*767px\)/)

	assert.match(navigation, /export function createInitialTurnWindow/)
	assert.match(navigation, /export function windowAfterPrepend/)
	assert.match(navigation, /export function createTurnNavigationItem/)
	assert.match(navigation, /export function restoreAnchoredScrollTop/)
	assert.match(navigation, /export function resolveTurnScrollElement/)
	assert.doesNotMatch(navigation, /estimateTurnHeight|sumTurnHeights/)
})
