const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')
const test = require('node:test')

const frontendRoot = path.resolve(__dirname, '../..')

function read(relativePath) {
	return fs.readFileSync(path.join(frontendRoot, relativePath), 'utf8')
}

test('chat page creates a conversation only on first send and refreshes the sidebar only after completed', () => {
	const entry = read('pages/ai-chat/index.vue')
	const page = read('components/user/workspace/user-chat-panel.vue')
	const workspace = read('components/user/user-workspace.vue')
	const pages = JSON.parse(read('pages.json'))
	const route = pages.pages.find(item => item.path === 'pages/ai-chat/index')

	assert.match(entry, /<user-workspace[\s\S]*initial-destination="chat"/)
	assert.equal(route?.style?.navigationStyle, 'custom')
	assert.match(page, /newChat\(\)[\s\S]*resetCurrentConversation\(\)/)
	assert.doesNotMatch(page, /newChat\(\)[\s\S]{0,300}aiConversationApi\./)
	assert.match(page, /event\.type === 'accepted'[\s\S]*setAcceptedConversation/)
	assert.match(page, /event\.type === 'completed'[\s\S]*\$emit\('conversation-completed'\)/)
	assert.match(workspace, /@conversation-completed="refreshConversations"/)
	assert.match(page, /Idempotency-Key|idempotencyKey/)
	assert.match(page, /this\.activeStream\?\.close/)
})

test('chat page sends and remembers the selected five-level reasoning effort', () => {
	const page = read('components/user/workspace/user-chat-panel.vue')

	assert.match(page, /REASONING_EFFORT_STORAGE_KEY/)
	assert.match(page, /Low[\s\S]*Medium[\s\S]*High[\s\S]*Extra High[\s\S]*Ultra/)
	assert.match(page, /selectedReasoningEffortLevel:\s*2/)
	assert.match(page, /supportedReasoningEffortLevels/)
	assert.match(page, /defaultReasoningEffortLevel/)
	assert.match(page, /@change="selectReasoningEffort"/)
	assert.match(page, /uni\.getStorageSync\(REASONING_EFFORT_STORAGE_KEY\)/)
	assert.match(page, /uni\.setStorageSync\(REASONING_EFFORT_STORAGE_KEY,\s*level\)/)
	assert.match(page, /reasoningEffortLevel:\s*this\.selectedReasoningEffortLevel/)
	assert.match(page, /:disabled="generating \|\| !selectedModel"/)
	assert.match(page, /selectModel\(event\)[\s\S]*normalizeReasoningEffortForModel/)
})

test('desktop chat uses one primary sidebar with new chat before navigation and recent after it', () => {
	const workspace = read('components/user/user-workspace.vue')
	const sidebar = read('components/user/user-workspace-sidebar.vue')
	const navigation = read('components/user/user-primary-navigation.vue')

	assert.equal((workspace.match(/<user-workspace-sidebar\b/g) || []).length, 1)
	assert.match(sidebar, /<template #before-items>[\s\S]*workspace-new-chat/)
	assert.match(sidebar, /<template #after-items>[\s\S]*<user-recent-conversations/)
	assert.ok(
		navigation.indexOf('<slot name="before-items"') <
			navigation.indexOf('class="user-primary-navigation-inner"')
	)
	assert.ok(
		navigation.indexOf('<slot name="after-items"') >
			navigation.indexOf('class="user-primary-navigation-inner"')
	)
	assert.match(navigation, /this\.\$emit\('destination-click', destination\)/)
	assert.doesNotMatch(navigation, /uni\.(?:navigateTo|navigateBack|redirectTo|reLaunch)\(/)
})

test('recent conversations are collapsed by default, lazy loaded, and shared with the mobile drawer', () => {
	const page = read('components/user/user-workspace.vue')
	const sidebar = read('components/user/user-workspace-sidebar.vue')
	const recent = read('components/user/user-recent-conversations.vue')
	const recentUsages = sidebar.match(/<user-recent-conversations\b/g) || []

	assert.match(page, /recentExpanded:\s*false/)
	assert.doesNotMatch(page, /onAuthenticatedPageReady\(\)[\s\S]{0,180}refreshConversations\(\)/)
	assert.match(page, /ensureRecentConversations\(\)[\s\S]*this\.conversationsLoaded/)
	assert.match(page, /toggleRecentConversations\(\)[\s\S]*this\.recentExpanded = !this\.recentExpanded[\s\S]*ensureRecentConversations\(\)/)
	assert.match(page, /selectDestination\(destination\)[\s\S]*destination === this\.activeDestination[\s\S]*windowWidth < 1024[\s\S]*openConversationDrawer\(\)[\s\S]*toggleRecentConversations\(\)/)
	assert.equal(recentUsages.length, 2)
	assert.match(recent, /:aria-expanded="String\(expanded\)"/)
	assert.match(recent, /:aria-controls="contentId"/)
	assert.match(recent, /:id="contentId"/)
	assert.match(recent, /v-if="expanded"/)
})

test('conversation public IDs are never rendered as body text and copy through the platform clipboard', () => {
	const page = read('components/user/user-workspace.vue')
	const recent = read('components/user/user-recent-conversations.vue')

	assert.doesNotMatch(recent, /\{\{\s*conversation\.conversationPublicId\s*\}\}/)
	assert.match(recent, /class="conversation-open"/)
	assert.match(recent, /class="conversation-copy"/)
	assert.doesNotMatch(recent, /<button[^>]*class="conversation-open"(?:(?!<\/button>)[\s\S])*<button/)
	assert.match(page, /copyConversationId\(conversationPublicId\)[\s\S]*uni\.setClipboardData\([\s\S]*data:\s*conversationPublicId/)
	assert.match(page, /会话 ID 已复制/)
	assert.doesNotMatch(page, /setStorageSync\([^)]*conversation/i)
})

test('chat page supports generic attachments while only media categories require model capabilities', () => {
	const page = read('components/user/workspace/user-chat-panel.vue')
	const cards = read('components/user/workspace/user-chat-attachment-list.vue')
	const upload = read('common/aichat/ai-conversation-upload.js')
	const state = read('common/aichat/ai-conversation-upload-state.js')
	const picker = read('common/aichat/ai-conversation-file-picker.js')
	const androidPicker = read('uni_modules/ait-document-picker/utssdk/app-android/index.uts')
	const androidUpload = read('uni_modules/ait-oss-put/utssdk/app-android/index.uts')

	assert.match(page, /chooseConversationFiles/)
	assert.match(picker, /uni\.chooseFile/)
	assert.match(picker, /chooseDocuments/)
	assert.match(androidPicker, /Intent\.ACTION_OPEN_DOCUMENT/)
	assert.match(androidPicker, /intent\.setType\('\*\/\*'\)/)
	assert.match(state, /if \(category === 'IMAGE'\) return 'IMAGE_INPUT'/)
	assert.match(state, /if \(category === 'AUDIO'\) return 'AUDIO_INPUT'/)
	assert.match(state, /if \(category === 'VIDEO'\) return 'VIDEO_INPUT'/)
	assert.match(state, /if \(!required \|\| !model\) return true/)
	assert.match(page, /image\/svg\+xml/)
	assert.match(cards, /image\/svg\+xml/)
	assert.match(upload, /MAX_CONCURRENCY = 3/)
	assert.match(upload, /MAX_FILE_BYTES = 100 \* 1024 \* 1024/)
	assert.match(upload, /MAX_TOTAL_BYTES = 200 \* 1024 \* 1024/)
	assert.match(upload, /AI_ATTACHMENT_TOTAL_SIZE_EXCEEDED/)
	assert.match(upload, /XMLHttpRequest/)
	assert.match(upload, /request\.upload\.onprogress/)
	assert.match(upload, /content-length/)
	assert.match(upload, /putFile/)
	assert.match(upload, /connection\?\.close/)
	assert.match(upload, /request\?\.abort/)
	assert.match(upload, /isRetryableUploadFailure/)
	assert.match(upload, /createPreuploads\(\[job\.declared\]\)/)
	assert.match(androidUpload, /setFixedLengthStreamingMode/)
	assert.match(androidUpload, /name\.lowercase\(\) == 'content-length'/)
	assert.doesNotMatch(upload, /authorizedRequest\([^)]*uploadUrl/)
	assert.match(page, /validateAttachmentSelection\(this\.pendingAttachments, selected\)/)
	assert.match(page, /this\.startAttachmentBatch\(files\)/)
	assert.match(page, /removed\.uploadTask\?\.cancel/)
	assert.match(page, /this\.cancelPendingUploads\(\)/)
	assert.match(page, /URL\?\.revokeObjectURL/)
	assert.match(page, /event\.type === 'completed'[\s\S]*releasePreviewUrls/)
	assert.match(cards, /pending-progress-ring/)
	assert.match(cards, /不受当前模型支持/)
})

test('audio attachments use the generic cross-platform open flow', () => {
	const page = read('components/user/workspace/user-chat-panel.vue')

	assert.doesNotMatch(page, /<audio\b/)
	assert.doesNotMatch(page, /previewAudio/)
	assert.match(page, /openAttachment\(attachment\)/)
	assert.match(page, /window\.open\(attachment\.url, '_blank', 'noopener,noreferrer'\)/)
	assert.match(page, /plus\.runtime\.openURL\(attachment\.url\)/)
	assert.match(page, /attachmentCategory\(file\)/)
})

test('attachments preupload immediately and gate sending until every file is ready', () => {
	const page = read('components/user/workspace/user-chat-panel.vue')
	const state = read('common/aichat/ai-conversation-upload-state.js')

	assert.match(page, /createPendingAttachment\(file, uuidV4\(\)\)/)
	assert.match(page, /startAttachmentBatch\(files\)/)
	assert.doesNotMatch(page, /ensureUploaded/)
	assert.match(page, /const attachmentRefs = selectedAttachments\.map\(file => file\.uploaded\)/)
	assert.match(state, /PREPARING[\s\S]*UPLOADING[\s\S]*UPLOADED[\s\S]*FAILED/)
	assert.match(state, /state !== ATTACHMENT_UPLOAD_STATES\.UPLOADED/)
	assert.match(state, /!isAttachmentCompatible\(file, model\)/)
	assert.match(page, /:disabled="!canSend"/)
	assert.match(page, /sendBlockedReason/)
})

test('finalization uses the activity event while showing attachment persistence progress', () => {
	const page = read('components/user/workspace/user-chat-panel.vue')

	assert.match(page, /event\.type === 'activity'/)
	assert.match(page, /activity\.phase === 'FINALIZING'/)
	assert.match(page, /saving:\s*true/)
	assert.match(page, /正在保存生成内容/)
	assert.match(page, /ATTACHMENT_STORAGE_PARTIAL/)
})

test('web search is capability gated and research events remain in session storage', () => {
	const page = read('components/user/workspace/user-chat-panel.vue')
	const capability = read('common/aichat/ai-conversation-web-search.js')
	const research = read('common/aichat/ai-conversation-research-session.js')

	assert.match(capability, /capabilities\.has\('RESPONSES'\)/)
	assert.match(capability, /capabilities\.has\('WEB_SEARCH'\)/)
	assert.match(page, /webSearchMode,/)
	assert.match(page, /role="switch"/)
	assert.match(page, /:aria-checked="String\(webSearchRequired\)"/)
	assert.match(page, /AI_CONVERSATION_WEB_SEARCH_MODES\.REQUIRED/)
	assert.match(page, /AI_CONVERSATION_WEB_SEARCH_MODES\.OFF/)
	assert.doesNotMatch(page, /<picker[\s\S]{0,300}webSearchOptions/)
	assert.match(page, /event\.type === 'activity'/)
	assert.match(page, /event\.type === 'source'/)
	assert.match(page, /event\.type === 'reasoning_summary'/)
	assert.match(page, /requestAnimationFrame|createAiConversationTextDrain/)
	assert.match(research, /globalThis\.sessionStorage/)
	assert.match(research, /MAX_STORAGE_BYTES = 2 \* 1024 \* 1024/)
	assert.match(research, /MAX_RECORDS = 20/)
	assert.match(research, /activityEventKeys/)
	assert.match(page, /eventId: String\(value\?\.eventId \|\| ''\)/)
	assert.match(page, /if \(activityAccepted === false\) return/)
	assert.match(page, /item\.activity\.eventId \|\| `activity-\$\{item\.activity\.sequence\}`/)
	assert.match(page, /STARTED:\s*'已开始'/)
	assert.match(page, /IN_PROGRESS:\s*'进行中'/)
	assert.match(page, /COMPLETED:\s*'已完成'/)
	assert.match(page, /FAILED:\s*'失败'/)
	assert.match(page, /UNAVAILABLE:\s*'不可用'/)
	assert.doesNotMatch(research, /localStorage/)
})

test('history reopening never merges Redis interrupted output into the visible timeline', () => {
	const page = read('components/user/workspace/user-chat-panel.vue')
	const api = read('common/aichat/ai-conversation-api.js')
	const store = read('common/aichat/ai-conversation-store.js')

	assert.match(page, /aiConversationApi\.messages/)
	assert.match(page, /discardTransientMessages/)
	assert.match(page, /markAiConversationHistoryStale/)
	assert.match(page, /resyncStaleHistory/)
	assert.match(page, /clearAiConversationHistoryStale/)
	assert.match(store, /filter\(message => Boolean\(message\.messagePublicId\)\)/)
	assert.doesNotMatch(api, /Redis|ephemeral/)
})

test('research recovery binds stored process to its exact persisted message', () => {
	const page = read('components/user/workspace/user-chat-panel.vue')
	const research = read('common/aichat/ai-conversation-research-session.js')

	assert.match(page, /bindMessage\?\.\(\s*event\.data\?\.messagePublicId/)
	assert.match(page, /messagePublicId:\s*message\.messagePublicId/)
	assert.doesNotMatch(page, /patchLatestMessage/)
	assert.match(research, /if \(messagePublicId != null\)/)
})

test('H5 and Android share one SSE parser and Android transport accepts POST JSON plus cancellation', () => {
	const h5 = read('common/aichat/ai-conversation-sse-h5.js')
	const android = read('common/aichat/ai-conversation-sse-app.js')
	const stream = read('common/aichat/ai-conversation-stream.js')
	const page = read('components/user/workspace/user-chat-panel.vue')
	const errorPresentation = read('common/aichat/ai-conversation-error-presentation.js')
	const uts = read('uni_modules/ait-sse/utssdk/interface.uts')
	const androidTransport = read('uni_modules/ait-sse/utssdk/app-android/index.uts')

	assert.match(h5, /createAiConversationSseParser/)
	assert.match(h5, /MAX_ERROR_BYTES = 16 \* 1024/)
	assert.match(h5, /boundedResponseText\(response\)[\s\S]*JSON\.parse/)
	assert.match(h5, /while \(total < MAX_ERROR_BYTES\)/)
	assert.match(h5, /error\.code = payload\?\.code/)
	assert.match(h5, /error\.statusCode = response\.status/)
	assert.match(android, /createAiConversationSseParser/)
	assert.match(android, /terminalReceived/)
	assert.match(android, /CLIENT_RESPONSE_HEADERS/)
	assert.match(androidTransport, /MAX_ERROR_BODY_BYTES = 16 \* 1024/)
	assert.match(androidTransport, /getErrorStream\(\)/)
	assert.match(androidTransport, /JSON\.parse\(body\)/)
	assert.match(androidTransport, /return \{ code, statusCode, message \}/)
	assert.match(androidTransport, /getContentType\(\)[\s\S]*text\/event-stream/)
	assert.match(stream, /Accept:\s*'text\/event-stream, application\/json'/)
	assert.match(stream, /if \(closed\) \{\s*active\.close\?\.\(closeReason, closeDetails\)\s*return\s*\}/)
	assert.match(android, /lifecycleDiagnostics\?\.abortCalled\?\.\(\)/)
	assert.match(errorPresentation, /AI_QUOTA_INSUFFICIENT:\s*'额度不足，请充值。'/)
	assert.match(page, /aiConversationErrorMessage\(error\)/)
	assert.match(page, /aiConversationErrorMessage\(\s*event\.data,\s*'模型响应未能完成'\s*\)/)
	assert.match(page, /error:\s*message/)
	assert.match(page, /this\.composerError = message/)
	assert.match(uts, /method:\s*string/)
	assert.match(uts, /body:\s*string/)
	assert.match(uts, /close:\s*\(\) => void/)
})

test('stream diagnostics connect browser reads, parsed SSE and rendered text without logging content', () => {
	const stream = read('common/aichat/ai-conversation-stream.js')
	const h5 = read('common/aichat/ai-conversation-sse-h5.js')
	const panel = read('components/user/workspace/user-chat-panel.vue')
	const diagnostics = read('common/aichat/ai-conversation-stream-diagnostics.js')

	assert.match(h5, /BROWSER_READ/)
	assert.match(stream, /BROWSER_SSE_PARSED/)
	assert.match(stream, /sequence: event\.data\?\.sequence/)
	assert.match(panel, /FRONTEND_RENDERED/)
	assert.match(panel, /clientPlatform\(\) === 'H5'/)
	assert.match(diagnostics, /ai_stream_client_timing_summary/)
	assert.doesNotMatch(diagnostics, /event\.data\.text/)
	assert.doesNotMatch(diagnostics, /console\.log/)
})
