package com.example.temperate.service.user.membership.payment;

/**
 * 该枚举是来稳定区分会员支付订单的输入、幂等、状态、历史和基础设施错误，供 Web 层映射精确 HTTP 状态。
 */
public enum MembershipPaymentErrorCode {
    FEATURE_DISABLED,
    PAYMENT_CHECKOUT_DISABLED,
    PAYMENT_PROVIDER_UNSUPPORTED,
    BAR_TIMEOUT,
    BAR_UNAVAILABLE,
    BAR_AUTH_FAILED,
    BAR_RESPONSE_INVALID,
    BAR_SIGNATURE_INVALID,
    BAR_ORDER_CONFLICT,
    LIUHAO_TIMEOUT,
    LIUHAO_UNAVAILABLE,
    LIUHAO_AUTH_FAILED,
    LIUHAO_RESPONSE_INVALID,
    LIUHAO_CHECKOUT_UNAVAILABLE,
    LIUHAO_SIGNATURE_INVALID,
    LIUHAO_ORDER_CONFLICT,
    LIUHAO_CLIENT_IP_UNAVAILABLE,
    LIUHAO_CREATE_OUTCOME_UNKNOWN,
    LIUHAO_CHECKOUT_REPLAY_UNAVAILABLE,
    PAYMENT_CREATE_OUTCOME_UNKNOWN,
    INPUT_INVALID,
    MEMBERSHIP_ORDER_NOT_FOUND,
    MEMBERSHIP_ORDER_IDEMPOTENCY_CONFLICT,
    MEMBERSHIP_ORDER_STATE_CONFLICT,
    MEMBERSHIP_PAYMENT_CALLBACK_IN_PROGRESS,
    MEMBERSHIP_TRANSITION_REJECTED,
    MEMBERSHIP_UPGRADE_HISTORY_MISSING,
    MEMBERSHIP_PAYMENT_AMOUNT_MISMATCH,
    MEMBERSHIP_PAYMENT_PROVIDER_TRADE_CONFLICT,
    MEMBERSHIP_PAYMENT_REDIS_UNAVAILABLE,
    MEMBERSHIP_PAYMENT_RABBIT_UNAVAILABLE
}
