package com.example.temperate.service.auth.login.enums;

/**
 * 枚举登录、验证码和会话流程可稳定映射的业务错误码。
 */
public enum LoginErrorCode {
    INVALID_INPUT,
    AUTHENTICATION_FAILED,
    LOGIN_BLOCKED,
    ACCOUNT_UNAVAILABLE,
    PASSWORD_RESET_REQUIRED,
    LOGIN_FLOW_NOT_FOUND,
    LOGIN_FLOW_EXPIRED,
    LOGIN_FLOW_FORBIDDEN,
    HUMAN_VERIFICATION_REQUIRED,
    TURNSTILE_REJECTED,
    VERIFICATION_COOLDOWN,
    VERIFICATION_SEND_LIMIT,
    VERIFICATION_CODE_EXPIRED,
    VERIFICATION_CODE_INVALID,
    SESSION_LIMIT_REACHED,
    INFRASTRUCTURE_UNAVAILABLE
}
