const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')
const test = require('node:test')

function source(relativePath) {
	return fs.readFileSync(path.resolve(__dirname, relativePath), 'utf8')
}

test('registers the membership offers page for Android while keeping payment results H5-only', () => {
	const pages = source('../../pages.json')
	const protectedRoutes = source('../../common/auth/protected-routes.js')
	const membershipPlansIndex = pages.indexOf('"path": "pages/account/membership-plans"')
	const paymentResultIndex = pages.indexOf('"path": "pages/account/payment-result"')
	const h5BlockBeforeMembership = pages.lastIndexOf('// #endif', membershipPlansIndex)
	const h5BlockBeforePaymentResult = pages.lastIndexOf('// #ifdef H5', paymentResultIndex)

	assert.ok(membershipPlansIndex > h5BlockBeforeMembership)
	assert.ok(h5BlockBeforePaymentResult > membershipPlansIndex)
	assert.ok(paymentResultIndex > h5BlockBeforePaymentResult)
	assert.doesNotMatch(protectedRoutes, /membership-plans|payment-result/)
})

test('membership plan page exposes only branded Liuhao H5 payment channels', () => {
	const page = source('membership-plans.vue')
	const alipayIcon = source('../../static/icons/payment/alipay.svg')
	const wechatIcon = source('../../static/icons/payment/wechat.svg')

	assert.match(page, /membershipPaymentApi\.offers\(\)/)
	assert.match(page, /membershipPaymentApi\.createOrder/)
	assert.match(page, /membershipPaymentApi\.startPayment/)
	assert.match(page, /order\.payAmountYuan\s*!==\s*offer\.payAmountYuan/)
	assert.match(page, /submitPaymentCheckout\(submission\)/)
	assert.match(page, /writePaymentReturnContext\(sessionStorage, order\.orderId\)/)
	assert.match(page, /LIUHAO_CHECKOUT_SUBMISSION_EXPIRED/)
	assert.match(page, /error\?\.code === 'LIUHAO_CHECKOUT_REPLAY_UNAVAILABLE'\s*&& order\?\.orderId/)
	assert.doesNotMatch(page, /LIUHAO_CHECKOUT_REPLAY_UNAVAILABLE'[\s\S]{0,120}\|\| error\?\.code === 'LIUHAO_CHECKOUT_UNAVAILABLE'/)
	assert.match(page, /六号已创建订单，但返回的支付入口暂时无法安全打开，请勿重复下单。/)
	assert.doesNotMatch(page, /createOrder\(\{[\s\S]{0,180}provider:/)
	assert.match(page, /paymentProviderLocked\s*=\s*true/)
	assert.match(page, /purchaseDisabled\(\)[\s\S]*?\|\| this\.paymentProviderLocked/)
	assert.match(page, /支付结果确认中/)
	assert.match(page, /PAYMENT_PROVIDER\s*=\s*'LIUHAO'/)
	assert.match(page, /label:\s*'支付宝渠道一'/)
	assert.match(page, /label:\s*'微信支付渠道一'/)
	assert.match(page, /icon:\s*'\/static\/icons\/payment\/alipay\.svg'/)
	assert.match(page, /icon:\s*'\/static\/icons\/payment\/wechat\.svg'/)
	assert.match(page, /startPayment\(orderId,\s*PAYMENT_PROVIDER\)/)
	assert.match(page, /submission\.provider\s*!==\s*PAYMENT_PROVIDER/)
	assert.doesNotMatch(page, /BAR 沙箱|支付提供方|双提供方/)
	assert.doesNotMatch(page, /PROVIDER_PRESENTATION|selectProvider\(|providerLabel\(/)
	assert.doesNotMatch(page, /google\.com\/s2\/favicons/)
	assert.match(alipayIcon, /fill="#1677FF"/)
	assert.match(wechatIcon, /fill="#07C160"/)
	assert.doesNotMatch(`${alipayIcon}\n${wechatIcon}`, /<script|(?:href|src)="https?:/i)
	// 浏览器提交描述过期也不能再次调用创建接口，否则可能为同一本地订单创建第二笔第三方订单。
	assert.equal((page.match(/membershipPaymentApi\.startPayment\(orderId,\s*PAYMENT_PROVIDER\)/g) || []).length, 1)
	assert.match(page, /:disabled="purchaseDisabled\(offer\)"/)
	assert.match(page, /@click="handleOfferAction\(offer\)"/)
	assert.doesNotMatch(page, /Flask|fetch\s*\(|window\.location\.assign|#token|payUrl|payUrlExpiresAt/)
	assert.doesNotMatch(page, /writePaymentReturnContext\([^)]*(?:fields|sign)/)
})

test('every App membership mode is read-only and returns before every H5 checkout call', () => {
	const page = source('membership-plans.vue')

	assert.match(page, /h5Client\(\)\s*\{[\s\S]*?\/\/ #ifdef H5[\s\S]*?return true[\s\S]*?\/\/ #ifndef H5[\s\S]*?return false/)
	assert.match(page, /appClient\(\)\s*\{[\s\S]*?return !this\.h5Client/)
	assert.match(page, /v-if="h5Client"[^>]*class="payment-method-block"/)
	assert.match(page, /只读报价/)
	assert.match(page, /App 客户端不创建订单、不提供支付/)
	assert.match(page, /App 客户端仅供查看/)
	assert.match(page, /handleOfferAction\(offer\)\s*\{[\s\S]*?if\s*\(this\.appClient\)[\s\S]*?this\.showAppUpgradeNotice\(offer\)[\s\S]*?return[\s\S]*?this\.purchase\(offer\)/)
	assert.match(page, /showAppUpgradeNotice\(offer\)\s*\{[\s\S]*?升级到 \$\{offer\.displayName\} 的当前费用为 ¥\$\{offer\.payAmountYuan\}/)
	assert.match(page, /niko000o\.site/)
	assert.match(page, /请前往网页版升级/)
	assert.match(page, /网页版升级维护中/)
	assert.match(page, /\/\/ #ifdef H5[\s\S]*?async purchase\(offer\)/)
	assert.doesNotMatch(page, /plus\.runtime\.openURL|uni\.setClipboardData|二维码/)
})

test('payment result page trusts only the authenticated local order query', () => {
	const page = source('payment-result.vue')

	assert.match(page, /membershipPaymentApi\.order\(this\.context\.orderId\)/)
	assert.match(page, /支付已由本项目后端确认/)
	assert.match(page, /POLL_INTERVAL_MILLIS\s*=\s*2000/)
	assert.match(page, /POLL_WINDOW_MILLIS\s*=\s*30000/)
	assert.doesNotMatch(page, /URLSearchParams|location\.search|ihaveagoddamnplan/)
})

test('profile quota panel exposes the upgrade entry with platform-specific guidance', () => {
	const profile = source('../../components/user/workspace/user-profile-panel.vue')
	const config = source('../../common/auth/config.js')

	assert.match(profile, /@click="openMembershipPlans"/)
	assert.match(profile, /升级套餐/)
	assert.match(profile, /查看 Go、Plus、Pro 与 Ultra 的服务端模拟支付报价/)
	assert.match(profile, /查看可升级套餐和实时价格，购买请前往网页版/)
	assert.match(config, /membershipPlans:\s*'\/pages\/account\/membership-plans'/)
	assert.match(config, /paymentResult:\s*'\/pages\/account\/payment-result'/)
})
